import { test } from 'node:test';
import assert from 'node:assert/strict';
import { contractors, matchContractors, parseQuery, type SearchParams } from './data.ts';
const base: SearchParams = { city: 'Алматы', date: '2026-10-03', category: 'Фотограф', budget: 250000, language: 'Русский', format: 'Свадьба', hours: 6 };
test('catalog contains 66 unique profiles', () => { assert.equal(contractors.length,66); assert.equal(new Set(contractors.map(c=>c.id)).size,66); });
test('returns at most three eligible recommendations with reasons', () => { const r=matchContractors(base); assert.equal(r.status,'success'); assert.equal(r.matches.length,3); r.matches.forEach(m=>{assert.ok(m.price<=base.budget);assert.ok(m.contractor.languages.includes(base.language));assert.ok(m.explanation.length>70);}); });
test('fully booked date excludes every candidate', () => { const r=matchContractors({...base,date:'2026-12-25'});assert.equal(r.status,'constraints_failed');assert.equal(r.matches.length,0);assert.ok(r.excluded.booked>0); });
test('low budget is distinct from missing category', () => { assert.equal(matchContractors({...base,budget:1}).status,'constraints_failed');assert.equal(matchContractors({...base,city:'Шымкент',category:'Видеограф'}).status,'category_missing'); });
test('December and duration surcharges are included before budget filtering', () => { const r=matchContractors({...base,date:'2026-12-01',hours:12,budget:1000000}); r.matches.forEach(m=>assert.equal(m.price,Math.round(m.contractor.price*1.3*2))); });
test('small pools return available candidates only', () => { const r=matchContractors({...base,budget:155000});assert.ok(r.matches.length<3);assert.ok(r.excluded.budget>0); });
test('extracts Russian parameters and retains unspecified fields', () => { const p=parseQuery('Видеограф на корпоратив в Астане 12 декабря до 300 тыс, казахский, 8 часов',base);assert.equal(p.category,'Видеограф');assert.equal(p.city,'Астана');assert.equal(p.budget,300000);assert.equal(p.date,'2026-12-12');assert.equal(p.hours,8);assert.equal(p.language,'Казахский');assert.equal(p.format,'Корпоратив');assert.deepEqual(parseQuery('',base),base); });
